### ISSUE TITLE
Fail to run `azd up`

### ISSUE THREAD

**Issue by NanaXiong00** [Azure-Samples/quote-of-the-day-dotnet#10]
**Describe the issue:**
When running the `azd up` command , the following error appears:
![image](https://github.com/user-attachments/assets/8839525c-7144-4582-96bc-7858d3fccbc2)
![image](https://github.com/user-attachments/assets/064834e2-29ed-4a9c-9fb2-17bdb914ee47)

**Repro Steps:**
1. Clone this repository.
2. Run `azd auth login`.
3. Run `azd init`.
4. Run `azd up`.

**Environment:**
- Azd version: azd version 1.9.6 (commit 0b1a8ad350177078312141f4465ad72205d7c077)
- OS: Windows

**Expected behavior:**
Run `azd up` successfully.

@hemarina and @amerjusupovic for notification.

**Comment by amerjusupovic** [comment]
I've linked a pull request which should fix the first errors above. The second image is related to a billing issue which I'm looking into and will have a solution for soon.

**Comment by NanaXiong00** [comment]
@amerjusupovic Based on the latest code test, running `azd up` results in the following new issues:
![image](https://github.com/user-attachments/assets/cc7054f0-e005-4d8c-be84-301c9c6a9597)
![image](https://github.com/user-attachments/assets/3bfb0b57-3866-4dbf-8f18-f43ea442c829)

**Comment by amerjusupovic** [comment]
First issue has been fixed, second one is a known issue right now with another team, working on talking to them.

**Comment by amerjusupovic** [comment]
I've been told the 500 error should be solved now, closing this again.

**Comment by NanaXiong00** [comment]
@amerjusupovic Based on the latest code test, the 500 error can no longer be reproduced, but the following error message still exists:
![image](https://github.com/user-attachments/assets/c182c3a5-1a79-4fd2-92dd-b8073e14e43b)

**Comment by NanaXiong00** [comment]
Thanks for your quick response, the latest test was successful!
